### ISSUE TITLE
Is the service broken ?

### ISSUE THREAD

**Issue by Mineaurel** [bridgedxyz/base#28]
I think the proxy might be broken. It worked just fine this morning 6 hours ago but now i'm getting blasted of errors 500 and Internal server errors even on app.cors.bridged.cc.
1 out of 10 request managed to succeed, so maybe are your servers overloaded ?

**Comment by aaronliunumber2** [comment]
Just wanted to chime in to add that I am also having problems using it.

**Comment by aaronliunumber2** [comment]
Update from me it seems to be OK now

**Comment by softmarshmallow** [comment]
You may want to check the request time when this happens again. the max timeout is set to 6 seconds. if any request that has large payload requires more than 6 seconds to fetch or deliver will respond with 500.

Sorry for the inconvenience. 

To add upon, there were no suspicious activity or server downtime AFAIK (from AWS stats).
We will notify users by issue on this github repository for further downtime notice or logic changes.

Please Watch this repository to get notified.
![image](https://user-images.githubusercontent.com/16307013/121833825-2a6ab200-cd08-11eb-8848-c3d0db603b43.png)

**Comment by softmarshmallow** [comment]
We've updated cloud usage policy, every application using base will have to be registered.
IMPORTANT - > https://github.com/bridgedxyz/base/issues/23
